
const nationalTeamCategories = [
    { label: 'Austria NT', type: 'team',value: 8, federation_id: 8 },
    { label: 'Ireland NT', type: 'team',value: 21, federation_id: 21 },
    { label: 'Great Britain NT', type: 'team',value: 20, federation_id: 20 },
    { label: 'Bulgaria NT', type: 'team',value: 10, federation_id: 10 },
    { label: 'Croatia NT', type: 'team',value: 15, federation_id: 15 },
    { label: 'Czechia NT', type: 'team',value: 6, federation_id: 6 },
    { label: 'Denmark NT', type: 'team',value: 149, federation_id: 149 },
    { label: 'Ukraine NT', type: 'team',value: 41, federation_id: 41 },
    { label: 'Italy NT', type: 'team',value: 2, federation_id: 2 },
    { label: 'Finland NT', type: 'team',value: 13, federation_id: 13 },
    { label: 'France NT', type: 'team',value: 14, federation_id: 14 },
    { label: 'Germany NT',type: 'team', value: 18, federation_id: 18 },
    { label: 'Greece NT', type: 'team',value: 151, federation_id: 151 },
    { label: 'Hungary NT', type: 'team',value: 42, federation_id: 42 },
    { label: 'Israel NT', type: 'team',value: 33, federation_id: 33 },
    { label: 'Netherlands NT', type: 'team',value: 1, federation_id: 1 },
    { label: 'Lithuania NT', type: 'team',value: 156, federation_id: 156 },
    { label: 'Malta NT', type: 'team',value: 25, federation_id: 25 },
    { label: 'Poland NT', type: 'team',value: 159, federation_id: 159 },
    { label: 'Spain NT', type: 'team',value: 39, federation_id: 39 },
    { label: 'Belgium NT', type: 'team',value: 143, federation_id: 143 },
    { label: 'Russia NT', type: 'team',value: 242, federation_id: 242 },
    { label: 'Slovakia NT', type: 'team',value: 37, federation_id: 37 },
    { label: 'Sweden NT', type: 'team',value: 34, federation_id: 34 },
    { label: 'Switzerland NT', type: 'team',value: 35, federation_id: 35 },
    { label: 'Turkey NT', type: 'team',value: 162, federation_id: 162 },
];

const italianClubCategories = [
    { label: 'A.S.D. REGGIO RAYS BASEBALL', type: 'team', value: 285 },
    { label: 'A.S.D. NETTUNO 2 BASEBALL CLUB', type: 'team', value: 329 },
    { label: 'MACERATA ANGELS A.S.D.', type: 'team', value: 330 },
    { label: 'A.S.D. SAN MARINO BASEBALL CLUB', type: 'team', value: 331 },
    { label: 'A.S.D. B.S.C. GODO', type: 'team', value: 332 },
    { label: '1949 PARMA BASEBALL CLUB ASD', type: 'team', value: 333 },
    { label: 'COLLECCHIO B.C. A.S.D.', type: 'team', value: 334 },
    { label: 'FORTITUDO BASEBALL CLUB 1953 S.S.D. scarl', type: 'team', value: 336 },
    { label: 'A.S.D. GRIZZLIES TORINO 48 B.S.C.', type: 'team', value: 337 },
    { label: 'CAGLIARI BASEBALL CLUB A.S.D.', type: 'team', value: 338 },
    { label: 'A.S.D. SENAGO MILANO UNITED B.C.', type: 'team', value: 340 },
    { label: 'BASEBALL CLUB SETTIMO A.S.D.', type: 'team', value: 342 },
    { label: 'CERVIGNANO BASEBALL E SOFTBALL A.S.D.', type: 'team', value: 343 },
    { label: 'A.S.D. BASEBALL TEAM VERONA', type: 'team', value: 344 },
    { label: 'NEW BLACK PANTHERS A.S.D.', type: 'team', value: 345 },
    { label: 'THUNDERS & DRAGONS  SOFTBALL -  BASEBALL A.S.D. CASTELLANA', type: 'team', value: 346 },
    { label: 'A.S.D. BOLZANO BASEBALL CLUB', type: 'team', value: 347 },
    { label: 'BOLOGNA ATHLETICS A.S.D.', type: 'team', value: 348 },
    { label: 'FIORENTINA BASEBALL  S.S.D. ARL', type: 'team', value: 349 },
    { label: 'A.S.D. BASEBALL CLUB SALA BAGANZA', type: 'team', value: 350 },
    { label: 'A.S.D. LONGBRIDGE 2000 BASEBALL CLUB', type: 'team', value: 351 },
    { label: 'S.S.D. MODENA B.S.C.- SOC. COOP.', type: 'team', value: 352 },
    { label: 'OLTRETORRENTE BASEBALL CLUB A.S.D.', type: 'team', value: 353 },
    { label: 'MONTEFIASCONE BASEBALL SOFTBALL 67 A.S.D.', type: 'team', value: 354 },
    { label: 'A.S.D. NETTUNO B.C. 1945', type: 'team', value: 355 },
    { label: 'LANCERS BASEBALL CLUB A.S.D.', type: 'team', value: 356 },
    { label: 'BASE BALL CLUB GROSSETO ASD', type: 'team', value: 357 },
    { label: 'SICILY RED SOX  A.S.D.', type: 'team', value: 358 },
    { label: 'A.S.D. CODOGNO BAS. `67', type: 'team', value: 359 },
    { label: 'MILANO 1946 BASEBALL E SOFTBALL A. S. D.', type: 'team', value: 360 },
    { label: 'POVIGLIO BASEBALL A.S.D.', type: 'team', value: 364 },
    { label: 'POLISPORTIVA PADULE BASEBALL -  A.S.D.', type: 'team', value: 366 },
    { label: 'A.S.D. BASEBALL SOFTBALL CLUB ROVIGO', type: 'team', value: 371 },
    { label: 'CROCETTA BASEBALL CLUB A.S.D.', type: 'team', value: 374 },
    { label: 'WHITE SOX BUTTRIO BASEBALL A.S.D.', type: 'team', value: 375 },
    { label: 'TORRE PEDRERA FALCONS BC ASS. SPORT. DILETT.', type: 'team', value: 381 },
    { label: 'BASEBALL SOFTBALL CLUB GROSSETO 1952 S.S.D. A R.L.', type: 'team', value: 383 },
    { label: 'A.S.D.  CATALANA BASEBALL SOFTBALL', type: 'team', value: 384 },
    { label: 'A.S.D. ACADEMY OF NETTUNO B.C.', type: 'team', value: 386 },
    { label: 'BOLLATE SOFTBALL 1969 A.S.D.', type: 'team', value: 387 },
    { label: 'SARONNO SOFTBALL  E BASEBALL A.S.D.', type: 'team', value: 390 },
    { label: 'A.B. CARONNO SOFTBALL ASD', type: 'team', value: 391 },
    { label: 'PIANORO SOFTBALL A.S.D.', type: 'team', value: 392 },
    { label: 'A.S.D. SESTESE SOFTBALL', type: 'team', value: 393 },
    { label: 'POL. CASERTA BAS. E SOFT. ACADEMY A.S.D.', type: 'team', value: 394 },
    { label: 'SOFTBALL CLUB FORLI` A.S.D.', type: 'team', value: 395 },
    { label: 'U.S. GIOVANILE COLLECCHIO SOFT. A.S.D.', type: 'team', value: 396 },
    { label: 'NEW BOLLATE A.S.D.', type: 'team', value: 397 },
    { label: 'LEGNANO BASEBALL  SOFTBALL A.S.D.', type: 'team', value: 398 },
    { label: 'A.S.D. AVIGLIANA REBELS', type: 'team', value: 399 },
    { label: 'A. S. D. NUORO SOFTBALL', type: 'team', value: 401 },
    { label: 'OLD PARMA BASEBALL SOFTBALL CLUB A.S.D.', type: 'team', value: 407 },
    { label: 'A.S.D. SOFTBALL MACERATA', type: 'team', value: 409 },
    { label: 'A.S.D. JUNIOR ALPINA B. E S.', type: 'team', value: 568 },
    { label: 'A.S.D. PADOVA BAS. SOFT. CLUB', type: 'team', value: 574 },
    { label: 'BRESCIA BASEBALL  SOFTBALL  ASS. SPORT. DIL.', type: 'team', value: 598 },
    { label: 'LION`S  BASEBALL NETTUNO A.S.D.', type: 'team', value: 635 },
    { label: 'BUSSOLENGO SOFTBALL 2.0 A.S.D.', type: 'team', value: 1282 },
    { label: 'NEW RIMINI BASEBALL SOFTBALL S.S.D. ARL', type: 'team', value: 1286 },
];


const dutchClubCategories = [
    { label: 'Neptunus', type: 'team', value: 287 },
    { label: 'Kinheim', type: 'team', value: 1263 },
    { label: 'HCAW', type: 'team', value: 1264 },
    { label: 'Hoofddorp Pioniers Baseball', type: 'team', value: 1265 },
    { label: 'Amsterdam Pirates Baseball', type: 'team', value: 1266 },
    { label: 'Quick Amersfoort Baseball', type: 'team', value: 1267 },
    { label: 'Storks', type: 'team', value: 1268 },
    { label: 'Twins Oosterhout', type: 'team', value: 1269 },
    { label: 'Olympia Haarlem', type: 'team', value: 1270 },
    { label: 'ROEF!', type: 'team', value: 1271 },
    { label: 'Sparks Haarlem', type: 'team', value: 1272 },
    { label: 'Onze Gezellen', type: 'team', value: 1273 },
    { label: 'Tex Town Tigers', type: 'team', value: 1274 },
    { label: 'Hoofddorp Pioniers Softball', type: 'team', value: 1306 },
    { label: 'Amsterdam Pirates Softball', type: 'team', value: 1307 },
    { label: 'Quick Amersfoort Softball', type: 'team', value: 1308 },
    { label: 'RCH-Pinguïns', type: 'team', value: 1521 },
    { label: 'UVV', type: 'team', value: 1825 },
    { label: 'Euro Stars', type: 'team', value: 2318 },
    { label: 'Red Lions', type: 'team', value: 2596 },
];

const austrianClubCategories = [
    { label: 'Vienna Wanderers', type: 'team', value: 1222 },
    { label: 'Vienna Metrostars', type: 'team', value: 1223 },
    { label: 'Attnang-Puchheim Athletics', type: 'team', value: 1224 },
    { label: 'Dornbirn Indians', type: 'team', value: 1225 },
    { label: 'Traiskirchen Grasshoppers', type: 'team', value: 1226 },
    { label: 'Wr. Neustadt Diving Ducks', type: 'team', value: 1227 },
    { label: 'Hard Bulls', type: 'team', value: 1228 },
    { label: 'Feldkirch Cardinals', type: 'team', value: 1229 },
    { label: 'Schwechat Blue Bats', type: 'team', value: 1261 },
    { label: 'Linz Witches und Bandits', type: 'team', value: 1276 },
];


const belgianClubCategories = [
    { label: 'Hoboken Pioneers', type: 'team', value: 1353 },
    { label: 'Stabroek Chicaboo`s', type: 'team', value: 1361 },
    { label: 'Deurne Spartans', type: 'team', value: 1377 },
    { label: 'Cantincrode Baseball en Softball Stars', type: 'team', value: 1394 },
    { label: 'Brasschaat Braves', type: 'team', value: 1414 },
    { label: 'Borgerhout Squirrels', type: 'team', value: 1473 },
    { label: 'Antwerp Eagles', type: 'team', value: 1474 },
    { label: 'Gent Knights', type: 'team', value: 1475 },
    { label: 'Merchtem Cats', type: 'team', value: 1476 },
    { label: 'Brussels Kangaroos', type: 'team', value: 1477 },
    { label: 'Namur Angels', type: 'team', value: 1478 },
    { label: 'Mont-Saint-Guibert Phoenix', type: 'team', value: 1479 },
    { label: 'Beveren Lions', type: 'team', value: 1480 },
    { label: 'Zonhoven Tigers', type: 'team', value: 1545 },
    { label: 'Braine Black Rickers', type: 'team', value: 1553 },
];


const czechClubCategories = [
    { label: 'SK Joudrs Praha', type: 'team', value: 1348 },
    { label: 'Beavers Chomutov', type: 'team', value: 1380 },
    { label: 'Žraloci Ledenice', type: 'team', value: 1381 },
    { label: 'Draci Brno', type: 'team', value: 1434 },
    { label: 'Arrows Ostrava', type: 'team', value: 1605 },
    { label: 'Painbusters Most', type: 'team', value: 1878 },
    { label: 'Eagles Praha', type: 'team', value: 2060 },
    { label: 'Hroši Brno', type: 'team', value: 2063 },
    { label: 'Sokol Hluboká', type: 'team', value: 2064 },
    { label: 'Technika Brno', type: 'team', value: 2065 },
    { label: 'Tempo Praha', type: 'team', value: 2066 },
    { label: 'Třebíč Nuclears', type: 'team', value: 2067 },
    { label: 'Blesk Jablonec', type: 'team', value: 2068 },
    { label: 'Kotlářka Praha', type: 'team', value: 2071 },
    { label: 'Olympia Blansko', type: 'team', value: 2072 },
    { label: 'SaBaT Praha', type: 'team', value: 2074 },
    { label: 'Skokani Olomouc', type: 'team', value: 2075 },
    { label: 'Hvězdy Extraligy', type: 'team', value: 2210 },
    { label: 'Chemie - Kotlářka', type: 'team', value: 2367 },
];


const frenchClubCategories = [
    { label: 'Les Comanches de Saint-Raphaël', type: 'team', value: 1352 },
    { label: 'Les Pharaons d`Evry-Courcouronnes', type: 'team', value: 1367 },
    { label: '3M Barracudas Baseball Université Club', type: 'team', value: 1385 },
    { label: 'Rouen Huskies', type: 'team', value: 1428 },
    { label: 'Sénart Templiers', type: 'team', value: 1435 },
    { label: 'Pessac Panthères', type: 'team', value: 1512 },
    { label: 'Les Grizzlys de Grenoble', type: 'team', value: 1513 },
    { label: 'Les Rabbits de Clapiers-Jacou', type: 'team', value: 1514 },
    { label: 'Metz Cometz', type: 'team', value: 1712 },
    { label: 'Stade Toulousain Baseball Softball', type: 'team', value: 1713 },
    { label: 'Les Boucaniers de La Rochelle', type: 'team', value: 1714 },
    { label: 'Les Lions de Savigny-sur-Orge', type: 'team', value: 1715 },
    { label: 'Cougars de Montigny-le-Bretonneux', type: 'team', value: 1716 },
    { label: 'Pirates de Béziers', type: 'team', value: 2309 },
    { label: 'BASEBALL CLUB DES HAUTS DE SEINE WILDCATS', type: 'team', value: 2627 },
];


const spanishClubCategories = [
    { label: 'Club de Béisbol y Sóftbol Rivas', type: 'team', value: 1354 },
    { label: 'Club Béisbol Viladecans', type: 'team', value: 1355 },
    { label: 'Tenerife Marlins Puerto Cruz', type: 'team', value: 1421 },
    { label: 'Astros Valencia', type: 'team', value: 1433 },
    { label: 'San Inazio Bilbao Bizkaia', type: 'team', value: 1622 },
    { label: 'Club Deportivo Arga', type: 'team', value: 1623 },
    { label: 'CS Fénix Valencia', type: 'team', value: 1624 },
    { label: 'Dridma Rivas Sófbol Club', type: 'team', value: 1625 },
    { label: 'CBS Cambre', type: 'team', value: 1626 },
    { label: 'OBB Bizkorrak', type: 'team', value: 1627 },
    { label: 'CBS Capitalinos Gran Canaria', type: 'team', value: 1628 },
    { label: 'Miralbueno Zaragoza', type: 'team', value: 1629 },
    { label: 'CBS Sant Boi', type: 'team', value: 1630 },
    { label: 'Club Béisbol Barcelona', type: 'team', value: 1648 },
    { label: 'CBS Antorcha Valencia', type: 'team', value: 1653 },
    { label: 'CBS Toros', type: 'team', value: 1654 },
    { label: 'Club Atlético Deportivo Irabia/Izaga', type: 'team', value: 1960 },
];


const tournamentCategories = [
        { value: 'BB-BUNDESLIGA', type: 'tournament', label: 'Baseball Bundesliga (AT)', federation_id: 8 },
        { value: 'SB-BUNDESLIGA', type: 'tournament', label: 'Softball Bundesliga (AT)', federation_id: 8 },
        { value: 'ESP-LNDH-BB', type: 'tournament', label: 'Liga Nacional de Béisbol Oro (ESP)', federation_id: 39 },
        { value: 'ESP-LNDH-SB', type: 'tournament', label: 'Liga Nacional de Sófbol Oro (ESP)', federation_id: 39 },
        { value: 'SLD1', type: 'tournament', label: 'Softball Ladies D1 (BE)', federation_id: 143 },
        { value: 'BD1', type: 'tournament', label: 'Baseball Men D1 (BE)', federation_id: 143 },
        { value: 'HOOFDKLASSE-SOFTBAL', type: 'tournament', label: 'Hoofdklasse Softbal (NL)', federation_id: 1 },
        { value: 'HOOFDKLASSE-HONKBAL', type: 'tournament', label: 'Hoofdklasse Honkbal (NL)', federation_id: 1 },
        { value: 'ITA-SERIE-A1-M-BB', type: 'tournament', label: 'Serie A Baseball (IT)', federation_id: 2 },
        { value: 'ITA-SERIE-A1-F-SB', type: 'tournament', label: 'Serie A1 Softball (IT)', federation_id: 2 },
        { value: 'CZE-EXL', type: 'tournament', label: 'Extraliga BB (CZ)', federation_id: 6 },
        { value: 'W-EXT-L', type: 'tournament', label: 'Extraliga SB (CZ)', federation_id: 148 },
        { value: 'FRA-D1BB', type: 'tournament', label: 'Championnat de France D1 BB (FR)', federation_id: 14 },
        { value: 'FRA-D1FSB', type: 'tournament', label: 'Championnat de France Division 1 Féminine SB (FR)', federation_id: 14 },
        { value: 'EU-CHAMP-W-SB', type: 'tournament', label: 'Women\'s Softball European Championship (EU)', federation_id: 278 },
        { value: 'EU-U-22-EURO-CHAMP-W-SB', type: 'tournament', label: 'U-22 Women’s Softball European Championship (EU)', federation_id: 278 },
        { value: 'EU-U-23-EURO-CHAMP-M-SB', type: 'tournament', label: 'U-23 Baseball European Championship (EU)', federation_id: 278 },
        { value: 'EU-EURO-PREM-CUP-W-SB', type: 'tournament', label: 'Women\'s Softball European Premiere Cup (EU)', federation_id: 278 },
        { value: 'EU-EURO-CUP-W-SB', type: 'tournament', label: 'Women’s Softball European Cup (EU)', federation_id: 278 },
        { value: 'EU-WINNERS-CUP-A-W-SB', type: 'tournament', label: 'Women’s Softball European Cup Winners Cup “A” (EU)', federation_id: 278 },
        { value: 'EU-WINNERS-CUP-B-W-SB', type: 'tournament', label: 'Women’s Softball European Cup Winners Cup “B” (EU)', federation_id: 278 },
        { value: 'EU-CHAMP-CUP-M-BB', type: 'tournament', label: 'European Baseball Champions Cup (EU)', federation_id: 278 },
        { value: 'EU-CHAMP-M-BB', type: 'tournament', label: 'Baseball European Championship (EU)', federation_id: 278 },
        { value: 'EU-U-18-EURO-CHAMP-W-SB', type: 'tournament', label: 'U-18 Women\'s European Softball Championship (EU)', federation_id: 278 },
        { value: 'EU-U-18-EURO-CHAMP-M-BB', type: 'tournament', label: 'U-18 European Baseball Championship (EU)', federation_id: 278 }


];

const statCategories = [
    { label: '10+ HR Season', type: 'seasonal_homeruns', value: 10 },
    { label: '15+ Hit Season', type: 'seasonal_hits', value: 15 },
    { label: '10+ SB Season', type: 'seasonal_sb', value: 10 },
    { label: '10+ BB Season', type: 'seasonal_bb', value: 10 },
    { label: '10+ Doubles Season', type: 'seasonal_doubles', value: 10 },
    { label: '5+ Triples Season', type: 'seasonal_triples', value: 5 },
    { label: '15+ RBI Season', type: 'seasonal_rbi', value: 15 },
    { label: '20+ RBI Season', type: 'seasonal_rbi', value: 20 },
    { label: '15+ Runs Season', type: 'seasonal_runs', value: 15 },
    { label: '20+ Runs Season', type: 'seasonal_runs', value: 20 },
    { label: '0.250+ wOBA Season (min. 10 pa)', type: 'seasonal_wOBA', value: 0.25 },
    { label: '0.300+ avg Season (min. 10 pa)', type: 'seasonal_avg', value: 0.3 },
    { label: '0.350+ OBP Season (min. 10 pa)', type: 'seasonal_avg', value: 0.35 },
    { label: '0.400+ OBP Season (min. 10 pa)', type: 'seasonal_avg', value: 0.4 },
    { label: '1.000+ OPS Season (min. 10 pa)', type: 'seasonal_ops', value: 1 },
    { label: '50k+ Season', type: 'seasonal_pitching_k', value: 50 },
    { label: '35k+ Season', type: 'seasonal_pitching_k', value: 35 },
    { label: '35 IP+ Season', type: 'seasonal_pitching_ip', value: 105 },
    { label: '50 IP+ Season', type: 'seasonal_pitching_ip', value: 105 },
    { label: '<3.00 ERA Season (min. 10 ip)', type: 'seasonal_pitching_era', value: 3 },
    { label: '<2.50 FIP Season (min. 10 ip)', type: 'seasonal_pitching_fip', value: 3 },
    { label: '3B (min 1 PA)', type: 'position', value: '3B' },
    { label: '1B (min 1 PA)', type: 'position', value: '1B' },
    { label: '2B (min 1 PA)', type: 'position', value: '2B' },
    { label: 'SS (min 1 PA)', type: 'position', value: 'SS' },
    { label: 'RF (min 1 PA)', type: 'position', value: 'RF' },
    { label: 'CF (min 1 PA)', type: 'position', value: 'CF' },
    { label: 'LF (min 1 PA)', type: 'position', value: 'LF' },
    { label: 'C (min 1 PA)', type: 'position', value: 'C' },
    { label: 'P (min 1 PA)', type: 'position', value: 'P' },

];


module.exports = {
    nationalTeamCategories,
    italianClubCategories,
    dutchClubCategories,
    austrianClubCategories,
    belgianClubCategories,
    spanishClubCategories,
    czechClubCategories,
    frenchClubCategories,
    statCategories,
    tournamentCategories,
};